### ISSUE TITLE
cannot `go get` with go 1.8 (anymore)

### ISSUE THREAD

**Issue by stephenmathieson** [github-release/github-release#101]
We use this tool in one of our release pipelines. We haven't changed any of our deployment stuff in a few months, but last night saw this error:

```
#!/bin/bash -eo pipefail
go get gopkg.in/aktau/github-release.v0
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

Exited with code exit status 1
```

It looks like we need to update our `go` version (we're still using 1.8) in order to be compatible with the `v0` line of this tool.

---

To reproduce, build this `Dockerfile`:

```Dockerfile
FROM golang:1.8
RUN go get gopkg.in/aktau/github-release.v0
```

---

Was dropping support for older `go` versions intentional?

**Comment by kevinburkemeter** [comment]
Hi, apologies, not intentional, but a consequence of adding a new dependency that depends on `golang.org/x/sys`, which uses `math/bits`.

I'm gonna work on reworking the dependency to avoid the extra import. In the meantime, you may want to try downloading a compiled binary directly; I'm not sure continuing to support a Go release that is six versions old is going to be a priority going forward.

Using the Dockerfile, you should be able to follow these steps to get a precompiled binary:

```
FROM golang:1.8
RUN curl --remote-name --silent --location "https://github.com/github-release/github-release/releases/download/v0.8.0/linux-amd64-github-release.bz2"
RUN apt-get update && apt-get install -y bzip2
RUN bzip2 -d linux-amd64-github-release.bz2 && chmod +x ./linux-amd64-github-release
RUN ./linux-amd64-github-release --version
```

**Comment by stephenmathieson** [comment]
I figured as much. Not a big deal, as we were able to manually tag/etc the project. Moving to a compiled binary is a good suggestion tho. I'll probably do that to avoid issues like this in the future.

For now, I just updated the image to use go v1.10 and everything seems fine.

**Comment by kevinburke** [comment]
Apologies, given you were able to workaround and Go 1.8 is now quite old, I would recommend you switch to a newer version or use a binary that was compiled with a newer Go.

**Comment by arungogosoon** [comment]
`go get` has been replaced with `go install` in 1.8 version. 
Refer this https://circleci.com/developer/images/image/cimg/go
