### ISSUE TITLE
Switching homebrew to use meterup fork

### ISSUE THREAD

**Issue by iainbethune** [github-release/github-release#99]
Since this repo seems pretty inactive, I created a PR on homebrew to update the github-release formula to use the @meterup @kevinburkemeter fork (https://github.com/meterup/github-release), starting with release 0.7.5.  This includes a fix for #97 among other things.  

See https://github.com/Homebrew/homebrew-core/pull/53891

**Comment by aktau** [comment]
Hi @iainbethune,

First of all: pretty inactive is an understatement. It's just under poor maintainership. I haven't prioritized working on this project since I started working for $DAY_JOB years ago.

So I'm happy that @kevinburke (AKA @kevinburkemeter I reckon) has agreed to take over maintainership.

You may have noticed that github.com/aktau/github-release now redirect to github.com/github-release/github-release.

Thanks Kevin for the offer of taking over maintainership, you'll serve the users much better than I did.

**Comment by kevinburke** [comment]
Thanks Nicolas! I believe this is resolved now so going to close.
